# -*- coding: utf-8 -*-
"""history_store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZouWJDzL7R7OE5JUiqz_Ehqs3w4m6w31
"""

# backend/app/storage/history_store.py

import json
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime
from app.core.paths import HISTORY_DIR

class HistoryStore:
    """
    data/history/{user_id}.json 파일에 오답 노트를 관리함
    """

    @staticmethod
    def _get_file_path(user_id: str) -> Path:
        return HISTORY_DIR / f"{user_id}.json"

    @staticmethod
    def load_history(user_id: str) -> Dict[str, Any]:
        file_path = HistoryStore._get_file_path(user_id)
        if not file_path.exists():
            return {"user_id": user_id, "wrong_items": {}} # wrong_items는 dict로 관리하여 업데이트 용이하게 함

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            return {"user_id": user_id, "wrong_items": {}}

    @staticmethod
    def save_attempt(user_id: str, question: Dict[str, Any], user_answer: str, is_correct: bool):
        """
        사용자 풀이를 저장하고, 오답인 경우 카운트를 증가시킴
        """
        history = HistoryStore.load_history(user_id)
        wrong_items = history.get("wrong_items", {})
        q_id = question["id"]

        now_iso = datetime.now().isoformat()

        if not is_correct:
            # 오답인 경우: 오답노트에 추가 또는 갱신
            if q_id in wrong_items:
                item = wrong_items[q_id]
                item["wrong_count"] += 1
                item["last_wrong_at"] = now_iso
                item["last_user_answer"] = user_answer
            else:
                # 신규 오답
                wrong_items[q_id] = {
                    "question_id": q_id,
                    "question": question["question"],
                    "last_user_answer": user_answer,
                    "correct_answer": str(question["answer"]), # MCQ 등 타입 대응
                    "explanation": question.get("explanation", ""),
                    "wrong_count": 1,
                    "last_wrong_at": now_iso
                }
        else:
            # 정답인 경우: (선택사항) 오답노트에서 제거할 수도 있고, 유지할 수도 있음.
            # 여기서는 '오답노트' 요구사항이므로 틀린 기록은 유지하되 로직에 따라 제거 가능.
            # 명세서상 별도 언급 없으므로 오답 기록은 유지.
            pass

        history["wrong_items"] = wrong_items

        # 파일 저장
        with open(HistoryStore._get_file_path(user_id), "w", encoding="utf-8") as f:
            json.dump(history, f, indent=2, ensure_ascii=False)

    @staticmethod
    def get_wrong_questions(user_id: str) -> List[Dict[str, Any]]:
        history = HistoryStore.load_history(user_id)
        # Dictionary 값을 List로 변환하여 반환
        return list(history.get("wrong_items", {}).values())