# -*- coding: utf-8 -*-
"""grading

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gdf1Nt9dSCXsUCXXjtmKC15RGBTfTuR8
"""

# backend/app/models/grading.py

from pydantic import BaseModel, Field

# --- 채점 (Grade) 관련 모델 ---

class GradeRequest(BaseModel):
    user_answer: str = Field(..., description="사용자가 선택하거나 작성한 답안")

class GradeResponse(BaseModel):
    question_id: str
    type: str  # MCQ or SAQ
    is_correct: bool
    score: int
    user_answer: str
    correct_answer: str
    feedback: str
    graded_at: str