# -*- coding: utf-8 -*-
"""history

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snFmBbbuYfwlFS84qtzLCNKFyh2nz2Fe
"""

from typing import List
from pydantic import BaseModel

# --- [수정됨] 명세서와 100% 일치시키기 위해 evidence 관련 필드 삭제 ---
class WrongQuestionItem(BaseModel):
    question_id: str
    question: str
    last_user_answer: str
    correct_answer: str
    explanation: str
    wrong_count: int
    last_wrong_at: str

    # evidence_page, evidence_image_url 제거함

# --- 오답노트 전체 응답 모델 ---
class WrongNoteResponse(BaseModel):
    user_id: str
    items: List[WrongQuestionItem]
    total: int

# --- 풀이 기록 로그 모델 (jsonl 저장용) ---
class HistoryLogEntry(BaseModel):
    timestamp: str
    pdf_id: str
    question_id: str
    user_answer: str
    is_correct: bool