# -*- coding: utf-8 -*-
"""grading

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqCl64k9lyiMYwfoUDb_Y35mt7SY5crD
"""

# backend/app/api/grading.py

from fastapi import APIRouter, HTTPException, Query
# [수정] Grade 관련은 grading에서, WrongNote 관련은 history에서 임포트
from app.models.grading import GradeRequest, GradeResponse
from app.models.history import WrongNoteResponse

from app.services.grading_service import GradingService
from app.services.history_service import HistoryService

router = APIRouter()

# 1. 사용자 답 채점 API
@router.post("/questions/{question_id}/grade", response_model=GradeResponse)
async def grade_user_answer(
    question_id: str,
    body: GradeRequest,
    pdf_id: str = Query(..., description="문제가 포함된 PDF의 ID"),
    user_id: str = Query("me", description="사용자 ID")
):
    try:
        response = GradingService.grade_answer(
            pdf_id=pdf_id,
            question_id=question_id,
            user_answer=body.user_answer,
            user_id=user_id
        )
        return response
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# 2. 오답노트 조회 API
@router.get("/users/me/wrong-questions", response_model=WrongNoteResponse)
async def get_my_wrong_questions(
    user_id: str = Query("me", description="사용자 ID")
):
    try:
        response = HistoryService.get_wrong_notes(user_id)
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))